### ISSUE TITLE
我本地通过One-Api配置了通义千问，通过Postman可以正常返回，使用AntSk尝试聊天却没有任何响应

### ISSUE THREAD

**Issue by SeptSkyTime** [xuzeyu91/AntSK#1]
以下是我的配置参数：
  "OpenAIOption": {
    "EndPoint": "http://localhost:3000/v1/chat/completions",
    "Key": "sk-998bc3456ce24c1fb5bf938d0666fxxx",
    "Model": "qwen-turbo",
    "EmbeddingModel": "qwen-turbo"
  },
请问上述配置有问题吗？为什么运行程序后，在聊天界面输入聊天内容后，就卡死了，长时间没有任何响应。
![image](https://github.com/xuzeyu91/AntSK/assets/141984875/fb56a894-8e78-4b71-905e-2c5704654612)

选择的应用为会话应用类型。
谢谢！

**Comment by xuzeyu91** [comment]
通义千问的role不支持assistant ，而SK使用的是assistant的角色，需要再httphandle中进行修改 
```
content = content.Replace("\"role\":\"system\""，"\"role\":\"user\"");// 替换清求字符串
```

**Comment by SeptSkyTime** [comment]
> httphandle

感谢答复，我试试！

**Comment by SeptSkyTime** [comment]
> 通义千问的role不支持assistant ，而SK使用的是assistant的角色，需要再httphandle中进行修改
> 
> ```
> content = content.Replace("\"role\":\"system\""，"\"role\":\"user\"");// 替换清求字符串
> ```

感谢答复，我试试！
