### ISSUE TITLE
支持哪些开源大语言模型呢?下载了google/gemma-7b

### ISSUE THREAD

**Issue by yeungxh** [xuzeyu91/AntSK#10]
使用方式会随着模型不同有所不同么

**Comment by xuzeyu91** [comment]
> 使用方式会随着模型不同有所不同么

使用llama.cpp的模型 gguf格式 国内比较好的推荐qwen

**Comment by xuzeyu91** [comment]
> 使用方式会随着模型不同有所不同么

使用方式是一样的 项目设计是兼容多模型  包括各种厂商提供的api也可以直接使用
