### ISSUE TITLE
请问我下载和安装antsk如何正常显示知识库页面？

### ISSUE THREAD

**Issue by zsl-007** [xuzeyu91/AntSK#15]
我下载了antsk，并且编译成功。下载安装了postgresql。下载了tinyllama-1.1b-chat-v1.0.Q8_0.gguf，修改了配置文件，成功运行了antsk.exe。现在问题是：
1、访问http://localhost:5000/，会跳转到http://localhost:5000/user/login，但是样式显示有点不正常，而且没有登录用户的地方。
2、不能访问：https://localhost:5001/llama/，不能正常显示你的知识库的页面。
请问如何正常安装和配置antsk。
我的配置文件如下：
[appsettings.json](https://github.com/xuzeyu91/AntSK/files/14478939/appsettings.json)

**Comment by zsl-007** [comment]
配置文件修改为："OpenAIOption": {
    "EndPoint": "http://localhost:5000/llama/",
    "Key": "",
    "Model": "gpt-3.5-turbo",
    "EmbeddingModel": "text-embedding-ada-002"
  },
但是访问http://localhost:5000/llama/会自动跳转到http://localhost:5000/user/login，并且显示不正常

**Comment by xuzeyu91** [comment]
> 配置文件修改为："OpenAIOption": {
>     "EndPoint": "http://localhost:5000/llama/",
>     "Key": "",
>     "Model": "gpt-3.5-turbo",
>     "EmbeddingModel": "text-embedding-ada-002"
>   },
> 但是访问http://localhost:5000/llama/会自动跳转到http://localhost:5000/user/login，并且显示不正常
> ![login](https://github.com/xuzeyu91/AntSK/assets/57434676/e73a205c-c517-47a4-b788-f8c31dfc6d7a)
> 

给key随便写个值看看可能异常了

**Comment by zsl-007** [comment]
找到问题了，项目目录下的wwwroot目录需要拷贝到项目目录下，解决了显示的问题。
但是现在有了新的问题，始终会在https://localhost:5001/user/login页面，用户名和密码输入后没有反应，浏览器调试发现报错。
![Uploading login_error.png…]()

**Comment by zsl-007** [comment]
找到问题了，重新生成之后，再发布，就可以了！！！
