### ISSUE TITLE
麻烦提供一下模型gguf文件下载链接

### ISSUE THREAD

**Issue by zsl-007** [xuzeyu91/AntSK#16]
能不能发一下，你的模型的gguf文件下载链接。
我使用我下载的模型tinyllama-1.1b-chat-v1.0.Q8_0.gguf，对话得到的结果很不理想，上传知识库文档也会报错。
![answer](https://github.com/xuzeyu91/AntSK/assets/57434676/fa47268a-8732-44da-81aa-21591138db8c)

**Comment by xuzeyu91** [comment]
https://hf-mirror.com/

**Comment by zsl-007** [comment]
能不能发一下你使用的tinyllama-1.1b-chat.gguf这个模型的下载地址，谢谢。
