### ISSUE TITLE
启动后样式找不到

### ISSUE THREAD

**Issue by heyunhang** [xuzeyu91/AntSK#17]
<img width="1086" alt="image" src="https://github.com/xuzeyu91/AntSK/assets/89768251/e0233840-bc35-4127-adab-80a3519a1dcc">

<img width="1077" alt="image" src="https://github.com/xuzeyu91/AntSK/assets/89768251/84dba689-3a18-4f17-98c3-c5dd1b4e17d9">

项目自己搭建环境，不是用compose启动的，启动后样式找不到
不知启动步骤是否有误，操作步骤如下
cd AntSK/AntSK
dotnet run

**Comment by xuzeyu91** [comment]
build一下再run试试

**Comment by xuzeyu91** [comment]
> <img alt="image" width="1086" src="https://private-user-images.githubusercontent.com/89768251/310054420-e0233840-bc35-4127-adab-80a3519a1dcc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3MDI2NTAsIm5iZiI6MTcwOTcwMjM1MCwicGF0aCI6Ii84OTc2ODI1MS8zMTAwNTQ0MjAtZTAyMzM4NDAtYmMzNS00MTI3LWFkYWItODBhMzUxOWExZGNjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA2VDA1MTkxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIzZGY1MDViZTk0NTgzM2ZjNjI0ZjkyMjMzNWJkODdhZjFkNWI5N2M5MTZlNjI0NjljNzNjOGZhMTRiZDA1MTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4ha1fro0EkHfmuiVRCCCJdbCUQpSoWCBGEwhS0DIQHQ"> <img alt="image" width="1077" src="https://private-user-images.githubusercontent.com/89768251/310055324-84dba689-3a18-4f17-98c3-c5dd1b4e17d9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3MDI2NTAsIm5iZiI6MTcwOTcwMjM1MCwicGF0aCI6Ii84OTc2ODI1MS8zMTAwNTUzMjQtODRkYmE2ODktM2ExOC00ZjE3LTk4YzMtYzVkZDFiNGUxN2Q5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA2VDA1MTkxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM1MGRiNDI1YmJlOTM5MDdiMDM5NWE5MDQwMjc1NTYwZDhmNGU3ZWIwZGE1YjY4MjE4MGRkNWExZmI1ZjFlYjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Divrs6sf20r9kEw3hLsv-X-B7ns7d5AptpRUsILpKNE">
> 项目自己搭建环境，不是用compose启动的，启动后样式找不到 不知启动步骤是否有误，操作步骤如下 cd AntSK/AntSK dotnet run

试试新版本是否还有此问题

**Comment by heyunhang** [comment]
找不到样式问题解决：
AntSK/src/AntSK下执行:
dotnet clean
dotnet build
dotnet publish "AntSK.csproj"
再去AntSK/src/AntSK/bin/Release/net8.0/publish下
dotnet AntSK.dll
然后就启动成功了
