### ISSUE TITLE
知识库连续上传文件会导致程序崩溃

### ISSUE THREAD

**Issue by langmansh** [xuzeyu91/AntSK#18]
首次启动程序上传一个txt程序正常
1.第二次接着上传一个或批量上传docx文件，控制台过了一会就直接停止了服务，页面就卡在那

![image](https://github.com/xuzeyu91/AntSK/assets/25790561/94940f29-32e0-4971-a520-af968c8634e6)

2.有时候上传docx文件的时候页面直接卡死，控制台有反应。但实际文件路劲下有文件，数据库未存进去

![image](https://github.com/xuzeyu91/AntSK/assets/25790561/242c9d0a-6429-471d-9515-aabf5de42462)

3.登录之后不管在哪个页面只要刷新之后立马就退出登录了

4.小问题，样式问题，嘿嘿，新增模型写了新增用户

![image](https://github.com/xuzeyu91/AntSK/assets/25790561/df847c47-1a9a-46a6-85c6-94e08dc2ef57)

5.当我对本地知识库进行第二次提问就开始报错，只能程序启动后提问一次

![image](https://github.com/xuzeyu91/AntSK/assets/25790561/0eb5e5b2-024f-4c40-a015-0391b1182325)
![image](https://github.com/xuzeyu91/AntSK/assets/25790561/7111dedc-6198-4dca-9dd1-2ff116654e47)

**Comment by xuzeyu91** [comment]
已修改为后台队列模式
