### ISSUE TITLE
AzureOpenAI的参数未经过调用

### ISSUE THREAD

**Issue by kele1006** [xuzeyu91/AntSK#20]
1、AzureOpenAI的调用参数需要调整
memory.WithAzureOpenAITextEmbeddingGeneration(new AzureOpenAIConfig() {
    APIKey = embedModel.ModelKey,
    Deployment = embedModel.ModelName,
    Endpoint = embedModel.EndPoint,
    Auth = AzureOpenAIConfig.AuthTypes.APIKey,
    APIType = AzureOpenAIConfig.APITypes.EmbeddingGeneration,
}, null, null, false, embeddingHttpClient);
需要指定Auth类型为ApiKey，否则会报错。

2、在KMService中， chatmodel与enbedModel在前端设置的时候需要更清晰的引导
//加载huihu 模型
 BuildTextGenerationByAIType(memory, chatModel, chatHttpClient);
 //加载向量模型
 BuildTextEmbeddingGenerationByAIType(memory, embedModel, embeddingHttpClient);

**Comment by xuzeyu91** [comment]
> 1、AzureOpenAI的调用参数需要调整 memory.WithAzureOpenAITextEmbeddingGeneration(new AzureOpenAIConfig() { APIKey = embedModel.ModelKey, Deployment = embedModel.ModelName, Endpoint = embedModel.EndPoint, Auth = AzureOpenAIConfig.AuthTypes.APIKey, APIType = AzureOpenAIConfig.APITypes.EmbeddingGeneration, }, null, null, false, embeddingHttpClient); 需要指定Auth类型为ApiKey，否则会报错。
> 
> 2、在KMService中， chatmodel与enbedModel在前端设置的时候需要更清晰的引导 //加载huihu 模型 BuildTextGenerationByAIType(memory, chatModel, chatHttpClient); //加载向量模型 BuildTextEmbeddingGenerationByAIType(memory, embedModel, embeddingHttpClient);

非常感谢您的建议

**Comment by xuzeyu91** [comment]
此问题已修复
