### ISSUE TITLE
关于StreamingChatMessageContent和StreamingTextContent的区别

### ISSUE THREAD

**Issue by kele1006** [xuzeyu91/AntSK#21]
这个版本中用StreamingTextContent替代了StreamingChatMessageContent，想知道两者之间的具体区别和对系统性能的影响，谢谢

**Comment by xuzeyu91** [comment]
在0.1.6.2版本中 已经取消了指定类型，由于LLamaSharp扩展不支持StreamingChatMessageContent，
而openai 和azure openai 对StreamingTextContent的支持又不是很好。
具体区别可以参考：https://learn.microsoft.com/en-us/dotnet/api/microsoft.semantickernel.streamingtextcontent?view=semantic-kernel-dotnet
https://learn.microsoft.com/en-us/dotnet/api/microsoft.semantickernel.streamingchatmessagecontent?view=semantic-kernel-dotnet

**Comment by xuzeyu91** [comment]
![95520565f5064ff19c4115506a1bbb8](https://github.com/xuzeyu91/AntSK/assets/26290929/39560234-2046-42bd-ae37-8aa81cd85df6)
