### ISSUE TITLE
Setting-ModelList错误

### ISSUE THREAD

**Issue by kele1006** [xuzeyu91/AntSK#27]
1、在AddModel的时候，判定模型存不存在的时候，需要过滤当前数据本身(update)。
AddModel-HandleSubmit

            if (_aimodels_Repositories.IsAny(p => p.AIModelType == _aiModel.AIModelType && p.EndPoint == _aiModel.EndPoint.ConvertToString() && p.ModelKey == _aiModel.ModelKey && p.ModelName == _aiModel.ModelName && p.Id != ModelId)) {
                _ = Message.Error("模型已存在！", 2);
                return;
            }
2、获取模型存放路径，当路径文件不存在时，建议增加默认路径 
_modelFiles = Directory.GetFiles(Path.Combine(Directory.GetCurrentDirectory(), LLamaSharpOption.FileDirectory));
                if (!string.IsNullOrEmpty(ModelPath)) {
                    _aiModel.AIType = Domain.Model.Enum.AIType.LLamaSharp;
                    _downloadModalVisible = true;

                    _downloadUrl = $"https://hf-mirror.com{ModelPath.Replace("---", "/")}";
                }

3、比较期待新的function的能力，以及通过function实现planner的编排。

**Comment by xuzeyu91** [comment]
> 1、在AddModel的时候，判定模型存不存在的时候，需要过滤当前数据本身(update)。
> AddModel-HandleSubmit
> 
>             if (_aimodels_Repositories.IsAny(p => p.AIModelType == _aiModel.AIModelType && p.EndPoint == _aiModel.EndPoint.ConvertToString() && p.ModelKey == _aiModel.ModelKey && p.ModelName == _aiModel.ModelName && p.Id != ModelId)) {
>                 _ = Message.Error("模型已存在！", 2);
>                 return;
>             }
> 2、获取模型存放路径，当路径文件不存在时，建议增加默认路径 
> _modelFiles = Directory.GetFiles(Path.Combine(Directory.GetCurrentDirectory(), LLamaSharpOption.FileDirectory));
>                 if (!string.IsNullOrEmpty(ModelPath)) {
>                     _aiModel.AIType = Domain.Model.Enum.AIType.LLamaSharp;
>                     _downloadModalVisible = true;
> 
>                     _downloadUrl = $"https://hf-mirror.com{ModelPath.Replace("---", "/")}";
>                 }
> 
> 3、比较期待新的function的能力，以及通过function实现planner的编排。

非常不错的提议 ，这个问题我们也已经注意到了

**Comment by ElderJames** [comment]
欢迎PR

**Comment by xuzeyu91** [comment]
已修复
