### ISSUE TITLE
使用本地模型对话时产生 Cannot add a user message after another user message (Parameter 'message')的错误

### ISSUE THREAD

**Issue by xgluxv** [xuzeyu91/AntSK#6]
下载了今天最新版的代码，使用LLamaSharp调用本地模型，Chat和Embedding模型都使用了：tinyllama-1.1b-chat-v1.0.Q4_K_M.gguf
导入知识库文件成功。
使用知识库对话后产生下面的错误：
![image](https://github.com/xuzeyu91/AntSK/assets/147598/725494b2-6355-411c-943c-269a3a93fbf5)

**Comment by xuzeyu91** [comment]
这个因为向量匹配相似度太低了 没有查到满足的

**Comment by xuzeyu91** [comment]
这个看起来是embedding已经完成 但是chat这里报错了 可能还是模型能力不太行

**Comment by xuzeyu91** [comment]
> 下载了今天最新版的代码，使用LLamaSharp调用本地模型，Chat和Embedding模型都使用了：tinyllama-1.1b-chat-v1.0.Q4_K_M.gguf
> 导入知识库文件成功。
> 使用知识库对话后产生下面的错误：
> ![image](https://github.com/xuzeyu91/AntSK/assets/147598/725494b2-6355-411c-943c-269a3a93fbf5)
> 

等明天我在试试怎么优化下本地模型的使用

**Comment by xuzeyu91** [comment]
> 下载了今天最新版的代码，使用LLamaSharp调用本地模型，Chat和Embedding模型都使用了：tinyllama-1.1b-chat-v1.0.Q4_K_M.gguf
> 导入知识库文件成功。
> 使用知识库对话后产生下面的错误：
> ![image](https://github.com/xuzeyu91/AntSK/assets/147598/725494b2-6355-411c-943c-269a3a93fbf5)
> 

这里可能有一个线程安全的bug

**Comment by xuzeyu91** [comment]
> 下载了今天最新版的代码，使用LLamaSharp调用本地模型，Chat和Embedding模型都使用了：tinyllama-1.1b-chat-v1.0.Q4_K_M.gguf 导入知识库文件成功。 使用知识库对话后产生下面的错误： ![image](https://private-user-images.githubusercontent.com/147598/308860934-725494b2-6355-411c-943c-269a3a93fbf5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkyNjg3MTYsIm5iZiI6MTcwOTI2ODQxNiwicGF0aCI6Ii8xNDc1OTgvMzA4ODYwOTM0LTcyNTQ5NGIyLTYzNTUtNDExYy05NDNjLTI2OWEzYTkzZmJmNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwMVQwNDQ2NTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04OWJhZDRkNzk0ZTZkNjZkZWI2MDAwYTM1Mzc1NGNjNzA4YTA2ZjM1YmM3YzA2NGY3NWMyM2JjNjA2ZTQwZjA1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.OemoLyG0mU6_Dtko-4c-93ZaAd9LlUGtRuaXUn81ap8)

在最新的代码中我已经解决了这个错误
