### ISSUE TITLE
代码编译报错

### ISSUE THREAD

**Issue by jiangguanghe** [xuzeyu91/AntSK#8]
代码下载来之后，编译报错了

严重性	代码	说明	项目	文件	行	禁止显示状态
错误	CS0115	“AppList.OnInitializedAsync()”: 没有找到适合的方法来重写	AntSK	D:\Code\AntSK-main\AntSK\Pages\AppPage\AppList.razor.cs	29	活动

一堆的这个错误

**Comment by xuzeyu91** [comment]
> 代码下载来之后，编译报错了
> 
> 严重性	代码	说明	项目	文件	行	禁止显示状态
> 错误	CS0115	“AppList.OnInitializedAsync()”: 没有找到适合的方法来重写	AntSK	D:\Code\AntSK-main\AntSK\Pages\AppPage\AppList.razor.cs	29	活动
> 
> 一堆的这个错误

应该是ide版本低了 可以使用dotnet build和dotnet run试试 如果没有报错说明需要更新vs版本

**Comment by jiangguanghe** [comment]
果真是，必须升级到vs2022最新版
