### ISSUE TITLE
目前好像只支持单个模型文件的加载，如果该模型有多个gguf文件如何加载

### ISSUE THREAD

**Issue by jiangguanghe** [xuzeyu91/AntSK#9]
![image](https://github.com/xuzeyu91/AntSK/assets/22929060/c3885be4-e938-433f-a7ad-5f35c2beb70c)
比如qianwen的7B模型有：
qwen1_5-7b-chat-q2_k.gguf
qwen1_5-7b-chat-q3_k_m.gguf
qwen1_5-7b-chat-q4_0.gguf
qwen1_5-7b-chat-q5_0.gguf
.........
等等多个文件，要加载这些模型文件，目前看是配置不了

**Comment by xuzeyu91** [comment]
这些是不同版本 用其中一个就可以了
